# Generated by Django 5.1.1 on 2024-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lessons_count',
            field=models.IntegerField(default=0),
        ),
    ]
